name: snp_call_nf 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bowtie2=2.4.4
  - gatk4=4.2.2.0
  - bedtools=2.30.0
  - samtools=1.13
  - bcftools=1.13
  - requests # for downloading files
